// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUkxRWH_MRmbMvLcdMeETx7oesXWJURA',
    appId: '1:168968310056:web:c8acad988011e19ed7141d',
    messagingSenderId: '168968310056',
    projectId: 'econaija-695be',
    authDomain: 'econaija-695be.firebaseapp.com',
    storageBucket: 'econaija-695be.appspot.com',
    measurementId: 'G-B8XK673GWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVYi_Kosupl-dJOy3Vv9ZHDg1vQ0_hBsg',
    appId: '1:168968310056:android:6b35cf3b3e2d5fb1d7141d',
    messagingSenderId: '168968310056',
    projectId: 'econaija-695be',
    storageBucket: 'econaija-695be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqK3BQaP5IdSucIW3K8QTGywI_hNolMgo',
    appId: '1:168968310056:ios:7eb774b8218be632d7141d',
    messagingSenderId: '168968310056',
    projectId: 'econaija-695be',
    storageBucket: 'econaija-695be.appspot.com',
    iosBundleId: 'com.example.econaija',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqK3BQaP5IdSucIW3K8QTGywI_hNolMgo',
    appId: '1:168968310056:ios:4705c1a7a1132a05d7141d',
    messagingSenderId: '168968310056',
    projectId: 'econaija-695be',
    storageBucket: 'econaija-695be.appspot.com',
    iosBundleId: 'com.example.econaija.RunnerTests',
  );
}
